services:
  - type: web
    name: akili-web-showcase
    plan: free
    runtime: python
    buildCommand: uv sync --frozen
    startCommand: uv run hypercorn src.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
