API_GATEWAY = "https://api.kiri.ng"

# Gateway authentication (must match GATEWAY_SECRET in Cloudflare Worker secrets)
GATEWAY_SECRET = "mobile-v1"
APP_VERSION = "1.0.0"
USER_AGENT = f"AkiliApp/{APP_VERSION}"

# Audio limits (must match gateway MAX_AUDIO_BODY_BYTES)
MAX_VOICE_DURATION_SEC = 60
MAX_AUDIO_SIZE_BYTES = 25 * 1024 * 1024  # 25MB


class AITaskType:
    TEXT = "text"
    VISION = "multimodal"  # kiri-gateway uses "multimodal" route for vision
    AUDIO = "audio"


DAILY_CREDITS = 150
CREDIT_COSTS = {
    "course_create": 15,
    "lesson_gen": 5,
    "quiz": 0,
    "mock_exam": 10,
    "tutor_question": 2,
    "tutor_media": 3,
    "study_plan": 5,
}

XP_REWARDS = {
    "lesson_complete": 10,
    "quiz_pass": 25,
    "quiz_perfect": 50,
    "mock_exam_complete": 100,
    "daily_streak": 15,
    "course_create": 20,
    "tutor_question": 5,
}

LEVELS = [
    {"name": "Freshman", "xp": 0, "icon": "🌱"},
    {"name": "Scholar", "xp": 200, "icon": "📚"},
    {"name": "Rising Star", "xp": 500, "icon": "⭐"},
    {"name": "Academic", "xp": 1000, "icon": "🎓"},
    {"name": "Prodigy", "xp": 2000, "icon": "🔬"},
    {"name": "Genius", "xp": 5000, "icon": "🧠"},
]

# System Templates (Used as fallbacks or suggestions)
SYSTEM_TEMPLATES = {
    "WAEC": {"name": "West African (WAEC)", "levels": ["JSS 1", "JSS 2", "JSS 3", "SSS 1", "SSS 2", "SSS 3"]},
    "K12": {"name": "International (Grade 1-12)", "levels": [f"Grade {i}" for i in range(1, 13)]},
    "UK": {"name": "UK / Commonwealth (Year 1-13)", "levels": [f"Year {i}" for i in range(1, 14)]},
    "CBC": {"name": "Competency-Based (Kenya/Others)", "levels": [f"Grade {i}" for i in range(1, 13)]},
    "UNI": {"name": "University / Higher Ed", "levels": ["Year 1", "Year 2", "Year 3", "Year 4", "Masters", "PhD"]},
}

# Source: ISO 3166-1 alpha-2 (Simplified list of all countries)
COUNTRIES = sorted(
    [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Andorra",
        "Angola",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cabo Verde",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Comoros",
        "Congo",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Cyprus",
        "Czechia",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Holy See",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "North Korea",
        "North Macedonia",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine State",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Samoa",
        "San Marino",
        "Sao Tome and Principe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Korea",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Suriname",
        "Sweden",
        "Switzerland",
        "Syria",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Tuvalu",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States of America",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe",
    ]
)
